[package]
name = "json2jsonl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.18.3"
serde = "1.0.228"
serde_json = { version="1.0.145", features  = ["raw_value"]}
