[package]
name = "json2jsonl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5", default-features = false, features = ["color", "derive", "std", "suggestions"] }
large-json-array = "0.1.1"
serde_json = "1.0"
